version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/qbconf
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

archives:
  - id: qbconf
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: qbconf
    homepage: "https://github.com/raftechio/qbconf"
    repository:
      owner: RaftechNL
      name: homebrew-toolbox
    install: |
      bin.install "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}" => "qbconf"
